services:
  https-portal:
    image: steveltn/https-portal:${HTTPS_PORTAL_VERSION}
    hostname: https-portal
    environment:
      DOMAINS: >
        ${HTTPS_PORTAL_HOSTNAME} -> http://app:80,
      CLIENT_MAX_BODY_SIZE: 1024M
      SERVER_NAMES_HASH_BUCKET_SIZE: 1024
      STAGE: ${HTTPS_PORTAL_MODE}
    volumes:
      - https-portal_certs:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PIPELINE_PHP_VERSION}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    hostname: app
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    expose:
      - 80
    tmpfs:
      - /var/www/html/storage/temp:mode=770,size=1m,uid=33,gid=33

volumes:
  https-portal_certs:

networks:
  default:
    name: ${EXTERNAL_NETWORK}
    external: true
