services:

  traefik:
    image: traefik:${TRAEFIK_VERSION:-3}
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.rule=Host(`${FQDN_TRAEFIK:-traefik.laravel-blog.test}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.service=api@internal"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    hostname: app
    environment:
      - VAULT_ENABLED=${VAULT_ENABLED}
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_DB_CREDENTIAL=${VAULT_DB_CREDENTIAL}
    secrets:
      - vault_token
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${FQDN_BLOG:-laravel-blog.test}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=80"
    tmpfs:
      - /var/www/html/storage/temp:mode=770,size=1m,uid=33,gid=33

networks:
  default:
    name: ${EXTERNAL_NETWORK}
    external: true

secrets:
  vault_token:
    environment: VAULT_TOKEN
